### PR TITLE
Clean up example 1

### PR DESCRIPTION
**Pull request by ibab**

### CODE REVIEW

**Comment by chrisburr** [comment]
How do you feel about using `matplotlib_hep` for the plot at the end?

Also this doesn't render correctly in github's viewer ([bug report](https://github.com/jupyter/nbviewer/issues/452)). Perhaps we should add a line at the top?

> This notebook is rendered incorrectly on the github web interface, [click here to see this file in the jupyter notebook viewer](http://nbviewer.jupyter.org/github/ibab/tensorprob/blob/master/examples/example1_particle_decays.ipynb).

**Comment by ibab** [comment]
Yeah, using `matplotlib_hep` for the physics examples is a good idea.
I think we can just remove the maths part at the beginning.

**Comment by chrisburr** [comment]
I think we should keep the maths part, I like it.

**Comment by ibab** [comment]
I've made some more changes (and unfortunately removed the maths).

**Comment by chrisburr** [comment]
I've just rebase this, I'll merge when the tests pass :+1:

**Pull request merged**
